### ISSUE TITLE
Duplicated function 

### ISSUE THREAD

**Issue by jb-sean** [garethr/openapi2jsonschema#23]
I was just reviewing the new changes you’ve been adding for support for different Kubernetes api version and group (thanks!) and noticed that there’s a function that is duplicated:
https://github.com/garethr/openapi2jsonschema/blob/master/openapi2jsonschema/command.py#L123-L142

**Comment by garethr** [comment]
Thanks, it came in as part of a merge and I'd just removed it. Thanks for flagging.
