### ISSUE TITLE
Incompatibility with python 3 and open local file instead of url

### ISSUE THREAD

**Issue by jcketz** [garethr/openapi2jsonschema#6]
Hi, thanks for your work, but I faced few problems:
Your code is Incompatible with python and you can't load a local file : here are the modifications for python3 compatibility and local file choice

```
import urllib
from urllib.request import Request, urlopen
...
    info("Downloading schema")
    if (urllib.parse.urlparse(schema).scheme != ""):
        req = Request(schema,headers={'User-Agent': 'Mozilla/5.0'})
        response = urllib.request.urlopen(req)
    else:
        response  = open(schema, "r")
    info("Parsing schema")
...
```

**Comment by consideRatio** [comment]
Dang - same for me, thanks for providing code @jcketz !

@garethr kubeval made me very happy recently by finding previously silent failures in `--strict` mode. But when used with kubernetes 1.10.4 or 1.9+ really the strict mode was lacking so I hoped to use these tools to get a schema and perhaps make a PR, but then I ran into this instead!

**Comment by garethr** [comment]
This should be fixed in master now.
